Repository Nexters/Rollingpaper_client, pull requests merged in 2020-08, with the labels that each got.

#18 메인 리스트 페이지 (main 1depth)
  components/Buttons.js
  pages/_app.js
  pages/_document.js
  pages/guide.js
  public/kakao.js
  styles/_font.scss
  styles/styles.scss
Labels: feature

#29 Feature/15 메인 2depth 상세 페이지
  components/Cards.js
  next.config.js
  package-lock.json
  package.json
  pages/_app.js
  pages/guide.js
  pages/receiver/detail.js
  pages/receiver/main.js
  styles/styles.scss
Labels: feature

#31 Fix #30 issue
  pages/receiver/detail.js
  styles/styles.scss
Labels: bug

#44 [#38] 준비자 페이지 메인 화면 구현
  components/Cards.js
  components/Header.js
  components/Layouts.js
  pages/receiver/detail.js
  pages/receiver/main.js
  pages/sender/main.js
Labels: feature

#53 에디터 배경색상 설정 모달 구성
  components/ColorModal.js
Labels: feature

#52 feature: Button, StickyFooter 스타일 변경 및 페이지 일괄 적용
  components/Buttons.js
  components/Layouts.js
  components/StickyFooter.js
  package-lock.json
  pages/guide.js
  pages/index.js
  pages/receiver/detail.js
  pages/receiver/main.js
  pages/sender/editor.js
  pages/sender/main.js
  pages/sender/share.js
Labels: feature

#61 feature: 아이콘 및 이미지 각 페이지에 적용
  components/Buttons.js
  components/Cards.js
  pages/receiver/detail.js
  pages/receiver/main.js
  pages/sender/main.js
  public/icons/back-light-icon.png
  public/icons/btn-add-image.png
  public/icons/btn-edit-align-focus.png
  public/icons/btn-edit-align.png
  public/icons/btn-edit-bg-focus.png
  public/icons/btn-edit-bg.png
  public/icons/btn-edit-camera-focus.png
  public/icons/btn-edit-camera.png
  public/icons/btn-edit-check.png
  public/icons/btn-edit-color-focus.png
  public/icons/btn-edit-color.png
  public/icons/btn-edit-typo-focus.png
  public/icons/btn-edit-typo.png
  public/icons/btn-trash-icon.png
  public/icons/download-light-icon.png
  public/icons/edit-active-icon.png
  public/icons/write-light-icon.png
  styles/styles.scss
Labels: feature

#74 feat: Card 글자수 넘칠 때 깨지는 이슈 수정
  components/Cards.js
  pages/receiver/detail.js
  pages/sender/editor.js
Labels: enhancement

#76 feat: Modal component 리팩토링 및 이름 변경 (#62)
  components/Cards.js
  components/DeleteModal.js
  components/Modal.js
  styles/styles.scss
Labels: enhancement

#105 feat: 메인 스티커 기능 (#89)
  .DS_Store
  components/Buttons.js
  components/StickerList.js
  components/StickerModal.js
  components/StickyFooter.js
  package-lock.json
  package.json
  pages/receiver/main.js
  pages/sender/main.js
  public/.DS_Store
  public/icons/.DS_Store
  public/icons/icon-delete.png
  public/images/img_frame_01.png
  public/images/img_frame_02.png
  public/images/img_frame_03.png
  public/images/img_frame_04.png
  public/images/main_sticker_01.png
  public/images/main_sticker_02.png
  public/images/main_sticker_03.png
  public/images/main_sticker_04.png
  public/images/main_sticker_05.png
  public/images/main_sticker_06.png
  public/images/main_sticker_07.png
  public/images/main_sticker_08.png
  public/images/main_sticker_09.png
  public/images/main_sticker_10.png
  public/images/main_sticker_11.png
  public/images/main_sticker_12.png
  public/images/main_sticker_13.png
  public/images/main_sticker_14.png
  public/images/main_sticker_15.png
  public/images/main_sticker_16.png
  public/images/main_sticker_17.png
  public/images/main_sticker_18.png
  public/images/main_sticker_19.png
  public/images/main_sticker_20.png
  public/images/main_sticker_21.png
  public/images/main_sticker_22.png
  public/images/main_sticker_23.png
  public/images/main_sticker_24.png
  public/images/main_sticker_25.png
  public/images/main_sticker_26.png
  public/images/main_sticker_27.png
  public/images/main_sticker_28.png
  services/rollingService.js
Labels: feature

#107 bug: zIndex 추가
  components/ColorModal.js
  components/FontModal.js
Labels: bug

#110 feat: framor-motion 추가
  .DS_Store
  components/Cards.js
  components/StickerList.js
  components/StickerModal.js
  package-lock.json
  package.json
  pages/_app.js
  public/.DS_Store
Labels: feature

#112 bug: Card background image 수정 및 sender/main 스티커 생성 버튼 fix
  .gitignore
  components/Cards.js
  components/ColorModal.js
  components/FontModal.js
  pages/receiver/detail.js
  pages/sender/detail.js
  pages/sender/editor.js
  pages/sender/main.js
  public/images/bg_card.png
Labels: bug

#116 enhancement: 스티커 기능 변경사항 수정
  components/StickerList.js
  pages/_app.js
  pages/sender/main.js
Labels: enhancement

#122 feat: textColor 종류 추가 및 공통 코드 컴포넌트화
  components/FontModal.js
Labels: feature

#127 feat: favicon 및 미리보기 이미지 변경, 사용하지 않는 이미지들 정리
  pages/_document.js
  public/browserconfig.xml
  public/icons/android-icon-144x144.png
  public/icons/android-icon-192x192.png
  public/icons/android-icon-36x36.png
  public/icons/android-icon-48x48.png
  public/icons/android-icon-72x72.png
  public/icons/android-icon-96x96.png
  public/icons/apple-icon-114x114.png
  public/icons/apple-icon-120x120.png
  public/icons/apple-icon-144x144.png
  public/icons/apple-icon-152x152.png
  public/icons/apple-icon-180x180.png
  public/icons/apple-icon-57x57.png
  public/icons/apple-icon-60x60.png
  public/icons/apple-icon-72x72.png
  public/icons/apple-icon-76x76.png
  public/icons/apple-icon-precomposed.png
  public/icons/apple-icon.png
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon-96x96.png
  public/icons/favicon.ico
  public/icons/main-icon.png
  public/icons/ms-icon-144x144.png
  public/icons/ms-icon-150x150.png
  public/icons/ms-icon-310x310.png
  public/icons/ms-icon-70x70.png
  public/images/IMG_0F4857AA6514-1.jpeg
  public/images/ballon-background.png
  public/images/kakao_login_medium_wide.png
  public/images/pen.jpeg
  public/images/q.jpeg
  public/images/r.png
  public/images/rolling.jpeg
  public/images/rollingpaper_thumbnail.png
  public/manifest.json
Labels: feature

#140 qa 요구사항 반영
  components/Buttons.js
  components/Cards.js
  components/ColorModal.js
  components/StickerList.js
  pages/index.js
  pages/sender/editor.js
  pages/sender/main.js
  pages/sender/share.js
Labels: enhancement
